version: '3.8'
services:
  ch1:
    build:
      context: .
      dockerfile: clickhouse1.Dockerfile
    volumes:
      - ./ch1/data:/var/lib/clickhouse
      - ./ch1/log:/var/log/clickhouse-server
    networks:
      - clickhouse
    privileged: true
    container_name: ch1
    ports:
      - '9000:9000'
      - '8123:8123'
      - '9009:9009'
    extra_hosts:
      - "server01:192.168.3.5"
      - "server02:192.168.3.5"
      - "server03:192.168.3.5"
    hostname: server01
    environment:
      - CH_SHARD=1
      - CH_REPLICA=server02

  ch2:
    build:
      context: .
      dockerfile: clickhouse2.Dockerfile
    volumes:
      - ./ch2/data:/var/lib/clickhouse
      - ./ch2/log:/var/log/clickhouse-server
    networks:
      - clickhouse
    privileged: true
    container_name: ch2
    ports:
      - '9001:9000'
      - '8124:8123'
      - '9010:9009'
    extra_hosts:
      - "server01:192.168.3.5"
      - "server02:192.168.3.5"
      - "server03:192.168.3.5"
    hostname: server02
    environment:
      - CH_SHARD=2
      - CH_REPLICA=server03

  ch3:
    build:
      context: .
      dockerfile: clickhouse3.Dockerfile
    volumes:
      - ./ch3/data:/var/lib/clickhouse
      - ./ch3/log:/var/log/clickhouse-server
    networks:
      - clickhouse
    privileged: true
    container_name: ch3
    ports:
      - '9002:9000'
      - '8125:8123'
      - '9011:9009'
    extra_hosts:
      - "server01:192.168.3.5"
      - "server02:192.168.3.5"
      - "server03:192.168.3.5"
    hostname: server03
    environment:
      - CH_SHARD=3
      - CH_REPLICA=server01

networks:
  clickhouse: