version: "3.2"
services:
  ch:
    build:
      context: .
      dockerfile: clickhouse.Dockerfile
      cache_from:
        - yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
    volumes:
      - ch_db:/var/lib/clickhouse
    networks:
      - clickhouse
    privileged: true
#    restart: always
#  tabix:
#    image: spoonest/clickhouse-tabix-web-client
#    ports:
#        - "8124:80"
#    networks:
#        - clickhouse
#    depends_on:
#        - ch
#    restart: always
#    privileged: true

networks:
  clickhouse:

volumes:
  ch_db: