version: '3.9'
services:
  keycloak:
    image: quay.mirrors.ustc.edu.cn/keycloak/keycloak:21.1.0
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://192.168.56.100:3306/keycloak?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 'root'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    ports:
      - "8800:8080"
      - "8843:8443"
    command: start --http-enabled=true --hostname-strict-https=false --hostname-strict=false --proxy=edge
