version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.4.1
    container_name: nacos
    environment:
      #PREFER_HOST_MODE: hostname #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台
      MODE: standalone
      MYSQL_SERVICE_HOST: 192.168.31.240
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      NACOS_APPLICATION_PORT: 8848
      JVM_XMS: 512m
      JVM_MMS: 320m
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./plugins/:/home/nacos/plugins
      - ./conf/application.properties:/home/nacos/conf/application.properties
    ports:
    - "8848:8848"