version: '3'
services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    privileged: true
    logging: 
      driver: "json-file"
      options: 
        max-size: "10m"
    environment:
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
      - TZ=Asia/Shanghai
    volumes:
      - ./elaticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elaticsearch/data:/usr/share/elasticsearch/data
      - ./elaticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:latest
    container_name: kibana
    privileged: true
    logging: 
      driver: "json-file"
      options: 
        max-size: "10m"
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - TZ=Asia/Shanghai
#    restart: always
    ports:
      - 5601:5601