version: '3.3'
services:
  sentinel:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8858:8858"
    container_name: sentinel
    networks:
      - sentinel
networks:
  sentinel:
    driver: bridge