version: "2.1"
services:
  jobmanager:
    image: flink:1.13.1
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./job/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
#    restart: always
 
  taskmanager:
    image: flink:1.13.1
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./task/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
#    restart: always
